import type { FeedGroup } from '~/types/feed'
import { getFavicon, getGhAvatar, getGhIcon, getQqAvatar, QqAvatarSize } from './utils/img'

export default [
	{
		name: '博客友链',
		desc: '优质独立博客收录',
		entries: [
			{
				author: '云云星羽',
				title: '云云星羽',
				desc: '陌让流年盼繁华，颜容依旧似繁花',
				link: 'https://starssr.com/',
				icon: 'https://cdn.sa.net/2024/08/04/vpQIDLfelPsiAzh.jpg',
				avatar: 'https://cdn.sa.net/2024/08/04/vpQIDLfelPsiAzh.jpg',
				date: '2021-07-18',
			},
			{
				author: '喵雨の小屋',
				title: '喵雨の小屋',
				desc: '努力学习中…',
				link: 'https://meowrain.cn',
				icon: 'https://cdn.sa.net/2024/08/04/lIgAyx7HnjPq8z5.jpg',
				avatar: 'https://cdn.sa.net/2024/08/04/lIgAyx7HnjPq8z5.jpg',
				date: '2021-07-18',
			},
			{
				author: 'Shanwer\'s Blog',
				title: 'Shanwer\'s Blog',
				desc: 'Shanwer的个人博客，不过是一个普通人记录的平凡日常而已:)',
				link: 'https://blog.shanwer.top',
				icon: 'https://cdn.sa.net/2024/08/04/cG7z1PY62tdQkZB.jpg',
				avatar: 'https://cdn.sa.net/2024/08/04/cG7z1PY62tdQkZB.jpg',
				date: '2021-07-18',
			},
			{
				author: '倾城于你',
				title: '倾城于你',
				desc: '一个热爱分享的Typecho小站。',
				link: 'https://qninq.cn',
				icon: 'https://cdn.sa.net/2024/08/04/KhUxXI6PONkMcBd.webp',
				avatar: 'https://cdn.sa.net/2024/08/04/KhUxXI6PONkMcBd.webp',
				date: '2021-07-18',
			},
			{
				author: 'Crant Blog',
				title: 'Crant Blog',
				desc: 'Crant Blog，是一个记录生活的个人博客，分享自己的心情、感悟、经历和创作。你可以在这里了解到 TimeMailX - 时光信件，一个可以给未来写封信的公益项目，也可以看到博主在不同城市的生活和对梦想的追求。',
				link: 'https://www.crant.cn',
				icon: 'https://cdn.sa.net/2025/08/19/ukK6BtcQRq7dLNA.png',
				avatar: 'https://cdn.sa.net/2025/08/19/ukK6BtcQRq7dLNA.png',
				date: '2021-07-18',
			},
			{
				author: '云深不知处',
				title: '云深不知处',
				desc: '不食人间烟火 且饮半杯风霜',
				link: 'https://www.lanzlz.cn',
				icon: 'https://cdn.sa.net/2024/08/04/ShokOnIsiHjfv7L.png',
				avatar: 'https://cdn.sa.net/2024/08/04/ShokOnIsiHjfv7L.png',
				date: '2021-07-18',
			},
			{
				author: '我不是咕咕鸽',
				title: '我不是咕咕鸽',
				desc: '服务器折腾不完全指南，定期分享一些好玩的东西，不定期记录生活。',
				link: 'https://blog.laoda.de',
				icon: 'https://cdn.sa.net/2024/08/04/IpsaCWvT2kcEVuy.jpg',
				avatar: 'https://cdn.sa.net/2024/08/04/IpsaCWvT2kcEVuy.jpg',
				date: '2021-07-18',
			},
			{
				author: '木因博客',
				title: '木因博客',
				desc: '心在哪里收获就在哪里',
				link: 'https://blog.muyin.site',
				icon: 'https://cdn.sa.net/2024/08/04/Z1tEOJScbjnQFVC.png',
				avatar: 'https://cdn.sa.net/2024/08/04/Z1tEOJScbjnQFVC.png',
				date: '2021-07-18',
			},
			{
				author: 'Yves\'s Blog',
				title: 'Yves\'s Blog',
				desc: 'Welcome!',
				link: 'https://blog.maoyiwei.com',
				icon: 'https://cdn.sa.net/2025/08/19/eLNivlYtwFoDyJu.jpg',
				avatar: 'https://cdn.sa.net/2025/08/19/eLNivlYtwFoDyJu.jpg',
				date: '2021-07-18',
			},
			{
				author: '小染笔记',
				title: '小染笔记',
				desc: '不为人知的角落开满了花',
				link: 'https://onoe.cn',
				icon: 'https://cdn.sa.net/2025/08/19/53TnMdtoZHUPpSG.jpg',
				avatar: 'https://cdn.sa.net/2025/08/19/53TnMdtoZHUPpSG.jpg',
				date: '2021-07-18',
			},
			{
				author: '华岁云小屋',
				title: '华岁云小屋',
				desc: '华岁的日常',
				link: 'https://www.vlo.cc',
				icon: 'https://cdn.sa.net/2025/08/19/yZlXxecS8BGmJfP.jpg',
				avatar: 'https://cdn.sa.net/2025/08/19/yZlXxecS8BGmJfP.jpg',
				date: '2021-07-18',
			},
			{
				author: '御坂秋生の小窝',
				title: '御坂秋生の小窝',
				desc: '不努力就只能听到别人的好消息',
				link: 'https://www.akio.top',
				icon: 'https://cdn.sa.net/2024/09/24/CRqSKDYNgprkaMG.jpg',
				avatar: 'https://cdn.sa.net/2024/09/24/CRqSKDYNgprkaMG.jpg',
				date: '2021-07-18',
			},
			{
				author: 'lead',
				title: 'lead',
				desc: '量化开发',
				link: 'https://ladfenemies.cc',
				icon: 'https://cdn.sa.net/2024/09/27/2wv9LfyWtZe5UdN.webp',
				avatar: 'https://cdn.sa.net/2024/09/27/2wv9LfyWtZe5UdN.webp',
				date: '2021-07-18',
			},
			{
				author: '大佬论坛',
				title: '大佬论坛',
				desc: '站长论坛，收集各路资源福利、主题插件，服务器主机、域名行情等内容。',
				link: 'https://www.dalao.net',
				icon: 'https://cdn.sa.net/2024/11/09/GjveTfAbUidx5PR.webp',
				avatar: 'https://cdn.sa.net/2024/11/09/GjveTfAbUidx5PR.webp',
				date: '2021-07-18',
			},
			{
				author: 'Jiewen\'blog',
				title: 'Jiewen\'blog',
				desc: '行动起来，活在当下。',
				link: 'https://jiewen.run',
				icon: 'https://www.jiewen.run/upload/jiewen_icon.png',
				avatar: 'https://www.jiewen.run/upload/jiewen_icon.png',
				date: '2021-07-18',
			},
			{
				author: '宇阳',
				title: '宇阳',
				desc: '记录所学知识，缩短和大神的差距！',
				link: 'https://liuyuyang.net',
				icon: 'https://cdn.sa.net/2025/02/26/iMrWySzlFoeNKmx.jpg',
				avatar: 'https://cdn.sa.net/2025/02/26/iMrWySzlFoeNKmx.jpg',
				date: '2021-07-18',
			},
			{
				author: '彬彬加冰',
				title: '彬彬加冰',
				desc: '想见你，不只是梦里',
				link: 'https://blog.wzwzx.cn',
				icon: 'https://cdn.sa.net/2025/07/25/r1hLyCFlc9BOTGS.jpg',
				avatar: 'https://cdn.sa.net/2025/07/25/r1hLyCFlc9BOTGS.jpg',
				date: '2021-07-18',
			},
			{
				author: '弦理智库',
				title: '弦理智库',
				desc: '往者不谏，来者可追',
				link: 'https://blog.zonox.top',
				icon: 'https://bu.dusays.com/2025/03/14/67d3fbedaa1c6.webp',
				avatar: 'https://bu.dusays.com/2025/03/14/67d3fbedaa1c6.webp',
				date: '2021-07-18',
			},
		],
	},
	{
		name: '失联网站',
		desc: '暂时失联的博客站点',
		entries: [
			{
				author: 'Ryan\'s Blog',
				title: 'Ryan\'s Blog',
				desc: '',
				link: 'https://www.moezz.cn',
				icon: 'https://cdn.sa.net/2024/08/04/dTwmZbVKsil4o8f.jpg',
				avatar: 'https://cdn.sa.net/2024/08/04/dTwmZbVKsil4o8f.jpg',
				date: '2021-07-18',
			},
		],
	},
] satisfies FeedGroup[]
