import type { FeedGroup } from '~/types/feed'
import { getFavicon, getGhAvatar, getGhIcon, getQqAvatar, QqAvatarSize } from './utils/img'

export default [
	{
		name: '网上邻居',
		desc: '哔——啵——电波通讯中，欢迎常来串门。',
		// @keep-sorted { "keys": ["date"] }
		entries: [
			{
				author: '陆小启',
				desc: '往者不谏，来者可追',
				link: 'https://blog.luxq.space',
				icon: 'https://cdn.sa.net/2025/09/01/Q7NJPrDvGkmS92u.jpg',
				avatar: 'https://cdn.sa.net/2025/09/01/Q7NJPrDvGkmS92u.jpg',
				archs: ['服务器'],
				date: '2025-09-14',
				comment: '手机用户进入时注意流量消耗',
			},
			{
				author: '彬彬加冰',
				desc: '今夜有雨',
				link: 'https://blog.wzwzx.cn',
				feed: 'https://blog.wzwzx.cn/rss.xml',
				icon: 'https://cdn.sa.net/2025/07/25/r1hLyCFlc9BOTGS.jpg',
				avatar: 'https://cdn.sa.net/2025/07/25/r1hLyCFlc9BOTGS.jpg',
				archs: ['Halo'],
				date: '2025-09-14',
			},
			{
				author: '宇阳',
				desc: '记录所学知识，缩短和大神的差距！',
				link: 'https://liuyuyang.net',
				feed: 'https://liuyuyang.net/api/rss',
				icon: 'https://cdn.sa.net/2025/02/26/iMrWySzlFoeNKmx.jpg',
				avatar: 'https://cdn.sa.net/2025/02/26/iMrWySzlFoeNKmx.jpg',
				archs: ['服务器'],
				date: '2025-09-14',
			},
			{
				author: 'Jiewen',
				desc: '行动起来，活在当下。',
				link: 'https://jiewen.run',
				feed: 'https://jiewen.run/rss.xml',
				icon: 'https://cdn.sa.net/2024/12/17/DXOtE5FBlJxra31.png',
				avatar: 'https://cdn.sa.net/2024/12/17/DXOtE5FBlJxra31.png',
				archs: ['Halo'],
				date: '2025-09-14',
			},
			{
				author: '大佬论坛',
				desc: '大佬论坛',
				link: 'https://www.dalao.net',
				icon: 'https://cdn.sa.net/2024/11/09/GjveTfAbUidx5PR.webp',
				avatar: 'https://cdn.sa.net/2024/11/09/GjveTfAbUidx5PR.webp',
				archs: ['服务器'],
				date: '2025-09-14',
			},
			{
				author: '御坂秋生の小窝',
				desc: '不努力就只能听到别人的好消息',
				link: 'https://www.akio.top',
				feed: 'https://www.akio.top/feed',
				icon: 'https://cdn.sa.net/2024/09/24/CRqSKDYNgprkaMG.jpg',
				avatar: 'https://cdn.sa.net/2024/09/24/CRqSKDYNgprkaMG.jpg',
				archs: ['Mix Space'],
				date: '2025-09-14',
			},
			{
				author: '小染笔记',
				desc: '不必借光而行，你我皆是星辰.',
				link: 'https://onoe.cn',
				feed: 'https://onoe.cn/rss.xml',
				icon: 'https://cdn.sa.net/2024/08/05/zU5x83MswrCpabm.jpg',
				avatar: 'https://cdn.sa.net/2024/08/05/zU5x83MswrCpabm.jpg',
				archs: ['Halo'],
				date: '2025-09-14',
			},
			{
				author: '清羽飞扬',
				desc: '柳影曳曳，清酒孤灯，扬笔撒墨，心境如霜',
				link: 'https://blog.liushen.fun',
				feed: 'https://blog.liushen.fun/atom.xml',
				icon: 'https://cdn.sa.net/2025/09/12/GreFw3BYu7agc2H.jpg',
				avatar: 'https://cdn.sa.net/2025/09/12/GreFw3BYu7agc2H.jpg',
				archs: ['Hexo'],
				date: '2025-09-14',
			},
			{
				author: '博客',
				desc: '量化开发',
				link: 'https://ladfenemies.cc',
				feed: 'https://ladfenemies.cc/feed',
				icon: 'https://cdn.sa.net/2024/09/27/2wv9LfyWtZe5UdN.webp',
				avatar: 'https://cdn.sa.net/2024/09/27/2wv9LfyWtZe5UdN.webp',
				archs: ['Next.js'],
				date: '2025-09-14',
			},
			{
				author: '华岁云小屋',
				desc: '华岁的日常',
				link: 'https://www.vlo.cc',
				icon: 'https://cdn.sa.net/2024/08/15/2Pe6M3EmVDlZ5sF.jpg',
				avatar: 'https://cdn.sa.net/2024/08/15/2Pe6M3EmVDlZ5sF.jpg',
				archs: ['Mix Space'],
				date: '2025-09-14',
			},
			{
				author: 'Yves',
				desc: 'Welcome!',
				link: 'https://blog.maoyiwei.com',
				feed: 'https://blog.maoyiwei.com/rss.xml',
				icon: 'https://cdn.sa.net/2024/08/04/nfJp8OgDZqXKaSW.png',
				avatar: 'https://cdn.sa.net/2024/08/04/nfJp8OgDZqXKaSW.png',
				archs: ['Halo'],
				date: '2025-09-14',
			},
			{
				author: '木因博客',
				desc: '心在哪里收获就在哪里。',
				link: 'https://blog.muyin.site',
				feed: 'https://blog.muyin.site/rss.xml',
				icon: 'https://cdn.sa.net/2024/08/04/Z1tEOJScbjnQFVC.png',
				avatar: 'https://cdn.sa.net/2024/08/04/Z1tEOJScbjnQFVC.png',
				archs: ['Halo'],
				date: '2025-09-14',
			},
			{
				author: '一事无成的伟大人生',
				desc: '',
				link: 'https://www.96mr.com',
				feed: 'https://www.96mr.com/index.php/feed',
				icon: 'https://cdn.sa.net/2024/08/04/ltpaQogn52xD6dk.jpg',
				avatar: 'https://cdn.sa.net/2024/08/04/ltpaQogn52xD6dk.jpg',
				archs: ['WordPress'],
				date: '2025-09-14',
			},
			{
				author: '我不是咕咕鸽',
				desc: 'VPS折腾不完全记录',
				link: 'https://blog.laoda.de',
				feed: 'https://blog.laoda.de/feed',
				icon: 'https://cdn.sa.net/2024/08/04/IpsaCWvT2kcEVuy.jpg',
				avatar: 'https://cdn.sa.net/2024/08/04/IpsaCWvT2kcEVuy.jpg',
				archs: ['Halo'],
				date: '2025-09-14',
			},
			{
				author: '云深不知处',
				desc: '不食人间烟火 且饮半杯风霜',
				link: 'https://www.lanzlz.cn',
				feed: 'https://www.lanzlz.cn/rss.xml',
				icon: 'https://cdn.sa.net/2024/08/04/ShokOnIsiHjfv7L.png',
				avatar: 'https://cdn.sa.net/2024/08/04/ShokOnIsiHjfv7L.png',
				archs: ['Halo'],
				date: '2025-09-14',
			},
			{
				author: '倾城于你',
				desc: '一个热爱分享的Typecho小站。',
				link: 'https://qninq.cn',
				feed: 'https://qninq.cn/feed',
				icon: 'https://cdn.sa.net/2024/08/04/KhUxXI6PONkMcBd.webp',
				avatar: 'https://cdn.sa.net/2024/08/04/KhUxXI6PONkMcBd.webp',
				archs: ['Typecho'],
				date: '2025-09-14',
			},
			{
				author: 'Forever',
				desc: '加入我的旅程，一起探索技术的无限可能。',
				link: 'https://xblog.aptzone.cc',
				feed: 'https://xblog.aptzone.cc/atom.xml',
				icon: 'https://cdn.sa.net/2024/08/04/MozXRagIwZqFOCp.jpg',
				avatar: 'https://cdn.sa.net/2024/08/04/MozXRagIwZqFOCp.jpg',
				archs: ['Hexo'],
				date: '2025-09-14',
			},
			{
				author: 'Shanwer',
				desc: '人生当苦无妨，良人当归即好。',
				link: 'https://blog.shanwer.top',
				feed: 'https://blog.shanwer.top/feed',
				icon: 'https://cdn.sa.net/2024/08/04/cG7z1PY62tdQkZB.jpg',
				avatar: 'https://cdn.sa.net/2024/08/04/cG7z1PY62tdQkZB.jpg',
				archs: ['WordPress'],
				date: '2025-09-14',
			},
			{
				author: '喵雨の小屋',
				desc: '努力学习中…',
				link: 'https://meowrain.cn',
				feed: 'https://meowrain.cn/feed',
				icon: 'https://cdn.sa.net/2024/08/04/lIgAyx7HnjPq8z5.jpg',
				avatar: 'https://cdn.sa.net/2024/08/04/lIgAyx7HnjPq8z5.jpg',
				archs: ['Halo'],
				date: '2025-09-14',
			},
			{
				author: '云云星羽',
				desc: '陌让流年盼繁华，颜容依旧似繁花。',
				link: 'https://starssr.com/',
				feed: 'https://starssr.com/rss.xml',
				icon: 'https://cdn.sa.net/2024/08/04/vpQIDLfelPsiAzh.jpg',
				avatar: 'https://cdn.sa.net/2024/08/04/vpQIDLfelPsiAzh.jpg',
				archs: ['Halo'],
				date: '2025-09-14',
			},
			{
				author: 'Crant',
				desc: '用心记录，美好生活。',
				link: 'https://www.crant.cn',
				feed: 'https://www.crant.cn/rss.xml',
				icon: 'https://cdn.sa.net/2025/09/15/OpkFjQ9WzdsTaZ6.png',
				avatar: 'https://cdn.sa.net/2025/09/15/OpkFjQ9WzdsTaZ6.png',
				archs: ['Halo'],
				date: '2025-09-14',
			},
                        {
                                author: '喜之梁',
                                desc: '多点关心多点爱',
                                link: 'https://blog.liang.one',
                                icon: 'https://blog.liang.one/favicon.ico',
                                avatar: 'https://bu.dusays.com/2025/10/02/68de1a78e7aa4.webp',
                                date: '2025-10-06',
                        },
                        {
                                author: 'Noah',
                                desc: '努力去发光，而不是被照亮',
                                link: 'https://blog.noah0932.top/',
                                feed: 'https://blog.noah0932.top/rss.xml',
                                icon: 'https://cdn.tulan.cyou/noah/2025/08/11/ab3ff3f0-ec7a-49d0-8875-d43c4a5b71fd-1.png',
                                avatar: 'https://cdn.tulan.cyou/noah/2025/07/26/b_5255bd8e31082e2a4332c4eb4172686e.jpg',
                                date: '2025-10-06',
                        },
                ],
        },
] satisfies FeedGroup[]